# Generated by Django 4.2.26 on 2025-11-22 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název kategorie')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název investice')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Investovaná částka')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aktuální hodnota')),
                ('investment_date', models.DateField(verbose_name='Datum investice')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investice',
                'verbose_name_plural': 'Investice',
                'ordering': ['-investment_date'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název subkategorie')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='expenses.category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Subkategorie',
                'verbose_name_plural': 'Subkategorie',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Částka')),
                ('description', models.CharField(max_length=200, verbose_name='Popis')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Příjem'), ('EXPENSE', 'Výdaj'), ('INVESTMENT', 'Investice (přesun)')], default='EXPENSE', max_length=20, verbose_name='Typ')),
                ('months_duration', models.IntegerField(default=0, verbose_name='Na kolik měsíců (0 = jednorázové)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum a čas zapsání')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum a čas editace')),
                ('payment_for', models.CharField(choices=[('SELF', 'Za sebe'), ('PARTNER', 'Za partnera'), ('SHARED', 'Společný účet')], default='SELF', max_length=20, verbose_name='Za koho placeno')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('approved', models.BooleanField(default=False, verbose_name='Schváleno')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Kdo zapsal')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.subcategory', verbose_name='Subkategorie')),
            ],
            options={
                'verbose_name': 'Transakce',
                'verbose_name_plural': 'Transakce',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Částka')),
                ('frequency_months', models.IntegerField(default=1, verbose_name='Frekvence (měsíce)')),
                ('next_payment_date', models.DateField(verbose_name='Datum další platby')),
                ('payment_for', models.CharField(choices=[('SELF', 'Za sebe'), ('PARTNER', 'Za partnera'), ('SHARED', 'Společný účet')], default='SHARED', max_length=20, verbose_name='Za koho placeno')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.category', verbose_name='Kategorie')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.subcategory', verbose_name='Subkategorie')),
            ],
            options={
                'verbose_name': 'Trvalá platba',
                'verbose_name_plural': 'Trvalé platby',
                'ordering': ['next_payment_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Měsíční limit')),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Varování při překročení')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_limits', to='expenses.category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Budget limit',
                'verbose_name_plural': 'Budget limity',
            },
        ),
    ]
