# Generated by Django 4.2.26 on 2025-11-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Investiční skupina', 'verbose_name_plural': 'Investiční skupiny'},
        ),
        migrations.RemoveField(
            model_name='investment',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='invested_amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investment_date',
        ),
        migrations.AddField(
            model_name='investment',
            name='observed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pozorovaná hodnota'),
        ),
        migrations.AddField(
            model_name='investment',
            name='observed_value_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum pozorované hodnoty'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='expenses.investment', verbose_name='Investiční skupina'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Název investiční skupiny'),
        ),
    ]
