# Generated by Django 4.2.26 on 2025-11-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='expenses.recurringpayment', verbose_name='Trvalá platba'),
        ),
    ]
