# Generated by Django 4.2.30 on 2026-04-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_transaction_is_imported_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Příjem'), ('EXPENSE', 'Výdaj')], default='EXPENSE', max_length=20, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Trvalá platba'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_name_per_category'),
        ),
    ]
