# Generated by Django 4.2.30 on 2026-05-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_recurring_start_date_paid_and_remove_tx_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringpayment',
            options={'ordering': ['start_date', 'name'], 'verbose_name': 'Trvalá platba', 'verbose_name_plural': 'Trvalé platby'},
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='note',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='payment_for',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='transaction_type',
        ),
    ]
