# Generated by Django 4.2.30 on 2026-05-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0010_remove_recurringpayment_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_recurring',
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jméno')),
                ('service_description', models.TextField(blank=True, verbose_name='Popis služby')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('frequency', models.CharField(blank=True, max_length=200, verbose_name='Frekvence')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Konec')),
                ('contact', models.TextField(blank=True, verbose_name='Kontakt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to=settings.AUTH_USER_MODEL, verbose_name='Vlastník')),
            ],
            options={
                'verbose_name': 'Instituce',
                'verbose_name_plural': 'Instituce',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='expenses.institution', verbose_name='Instituce'),
        ),
    ]
