# Generated by Django 4.2.30 on 2026-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_institution_and_transaction_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='permanent',
            field=models.BooleanField(default=False, help_text='Dlouhodobá závazná platba, obtížně zrušitelná', verbose_name='Trvalé'),
        ),
    ]
