# Generated by Django 4.2.30 on 2026-05-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_recurring_payment_permanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Opakující se'),
        ),
    ]
